services:
  qbit-discord-bot:
    image: ghcr.io/urfatandihateu/qbit-discord-bot:1.0.0
    container_name: qbit-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - QBIT_HOST=${QBIT_HOST}
      - QBIT_USER=${QBIT_USER}
      - QBIT_PASS=${QBIT_PASS}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - POLL_INTERVAL=${POLL_INTERVAL:-12}
